<?php
/**
 * Created by PhpStorm.
 * User: dsmrt
 * Date: 1/12/18
 * Time: 9:33 PM
 */

namespace flipbox\keychain\records;


use flipbox\ember\records\ActiveRecord;
use flipbox\ember\records\traits\StateAttribute;
use flipbox\keychain\KeyChain;

/**
 * Class KeyChainRecord
 * @package flipbox\keychain\records
 * @property string $certificate
 * @property string $key
 */
class KeyChainRecord extends ActiveRecord
{

    use StateAttribute;

    public $decryptedKey;
    public $decryptedCertificate;

    /**
     * The table alias
     */
    const TABLE_ALIAS = 'keychain';

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {

        KeyChain::getInstance()->getService()->encrypt($this);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Call to fetch key using the getter decrypts
     * @return bool|string
     */
    public function getDecryptedKey()
    {
        if (! $this->decryptedKey) {
            KeyChain::getInstance()->getService()->decrypt($this);
        }

        return $this->decryptedKey;
    }

    /**
     * Call to fetch certificate using the getter decrypts
     * @return bool|string
     */
    public function getDecryptedCertificate()
    {
        if (! $this->decryptedCertificate) {
            KeyChain::getInstance()->getService()->decrypt($this);
        }

        return $this->decryptedCertificate;
    }

}